### ISSUE TITLE
Implement robust and configurable logging

### ISSUE THREAD

**Issue by manavgup** [manavgup/rag_modulo#46]
Currently logging levels are defined across multiple files. Need a consistent approach to logging.

**Comment by Calseon** [comment]
I'll pick this up and start looking at it

**Comment by Calseon** [comment]
I took a look at our [logging_utils](https://github.com/manavgup/rag_modulo/blob/main/backend/core/logging_utils.py) and other files using the logger. I'm not sure how to improve them actually, the current setup looks fine to me?

I'll un-assign myself from this Issue for now and switch to working on UI, if there's more to be done let me know

**Comment by manavgup** [comment]
Thank you for reviewing. I will close this for now.
