### ISSUE TITLE
collections exist but not visible in CollectionForm.js

### ISSUE THREAD

**Issue by manavgup** [manavgup/rag_modulo#6]
see browser console log. Collection exists but not visible in the UI. @luizerico 

User data from server: {user: {…}}
api.js:62 API_ROUTES.GET_USER_COLLECTIONS: /user-collections/
api.js:63 User UUID: 084fdd9d-f6f8-485c-ad3e-bc66c561805b
api.js:65 Full URL: /user-collections/084fdd9d-f6f8-485c-ad3e-bc66c561805b
authService.js:25 Fetching user data...
authService.js:26 All cookies: 
authService.js:31 Session response: Response {type: 'basic', url: 'http://localhost:3000/api/auth/session', redirected: false, status: 200, ok: true, …}
authService.js:34 User data from server: {user: {…}}
api.js:68 User collections response: {data: {…}, status: 200, statusText: 'OK', headers: Li, config: {…}, …}

<img width="753" alt="image" src="https://github.com/user-attachments/assets/bb032f21-54e5-4211-9f97-b0beb853d53b">

**Comment by mtykhenko** [comment]
Collections are visible + REST API endpoints were merged/cleaned up

Let’s discuss what screens/capabilities are required for MVP and beyond

**Comment by mtykhenko** [comment]
Done
